# Generated by Django 4.2.3 on 2023-08-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url_video',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
