# Generated by Django 4.2.3 on 2023-08-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='url_video',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
