# Generated by Django 4.2.3 on 2023-08-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_lesson_url_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='link',
        ),
    ]
